# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Zip and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish_release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Zip File
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip ./
      - name: Create release
        id: create_release
        run: |
          set -xe
          RELDATE="$(date +'%Y-%m-%d %H:%M')"
          NAME="Auto-Build $RELDATE"
          TAGNAME="autobuild-$(date +'%Y-%m-%d-%H-%M')"
          hub release create -a release.zip -m "$NAME" -t "main" "$TAGNAME"
        env:
          GITHUB_TOKEN: ${{ github.token }}